[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DeviceLayout = "ebf59a4a-04ec-49d7-8cd4-c9382ceb8e85"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSONSchema = "7d188eb4-7ad8-530c-ae41-71a32a6d4692"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
PRIMA = "0a7d04aa-8ac2-47b3-b7a7-9dbd6ad661ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
DeviceLayout = "=1.8.0"
